apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flowboard

resources:
  - namespaces/namespace.yaml
  - postgres/postgres.yaml
  - postgres/postgres-deployment.yaml
  - postgres/postgres-service.yaml
  - backend/backend-deployment.yaml
  - backend/backend-service.yaml
  - backend/backend-hpa.yaml
  - frontend/frontend-deployment.yaml
  - frontend/frontend-service.yaml
  - frontend/frontend-hpa.yaml

images:
  - name: ghcr.io/gorinovdan/devopslabs/backend
    newTag: latest
  - name: ghcr.io/gorinovdan/devopslabs/frontend
    newTag: latest

labels:
  - pairs:
      app.kubernetes.io/part-of: flowboard
      app.kubernetes.io/managed-by: argocd
    includeSelectors: false
    includeTemplates: false
