apiVersion: v1
kind: Service
metadata:
  name: sonar-postgres
  namespace: sonarqube
spec:
  type: ClusterIP
  selector:
    app: sonar-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
