#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

AUTO_START_MINIKUBE="${AUTO_START_MINIKUBE:-1}" \
BUILD_LOCAL="${BUILD_LOCAL:-1}" \
BUILD_OBSERVABILITY_LOCAL="${BUILD_OBSERVABILITY_LOCAL:-1}" \
ENABLE_OBSERVABILITY="${ENABLE_OBSERVABILITY:-1}" \
ENABLE_PORT_FORWARD="${ENABLE_PORT_FORWARD:-1}" \
PROMETHEUS_IMAGE="${PROMETHEUS_IMAGE:-flowboard-prometheus:local-2.54.1}" \
GRAFANA_IMAGE="${GRAFANA_IMAGE:-flowboard-grafana:local-11.2.2}" \
RUN_SMOKE_TEST="${RUN_SMOKE_TEST:-1}" \
RUN_HPA_VALIDATION="${RUN_HPA_VALIDATION:-0}" \
"${ROOT_DIR}/scripts/deploy_minikube.sh"
